/*
 MelonJS Game Engine
 Copyright (C) 2012, Olivier BIOT
 http://www.melonjs.org

 melonJS is licensed under the MIT License.
 http://www.opensource.org/licenses/mit-license.php

 Tween JS
 https://github.com/sole/Tween.js
*/
(function(b,c){function a(){if(!i){if(!d.body)return setTimeout(a,13);d.removeEventListener?d.removeEventListener("DOMContentLoaded",a,!1):b.removeEventListener("load",a,!1);i=!0;for(var e=0;e<h.length;e++)h[e].call(b,[]);h=[]}}function e(){return{xmlDoc:null,parser:null,parseFromString:function(a){b.DOMParser?(this.parser=new DOMParser,this.xmlDoc=this.parser.parseFromString(a,"text/xml")):(this.xmlDoc=new ActiveXObject("Microsoft.XMLDOM"),this.xmlDoc.async="false",this.xmlDoc.loadXML(a));null==
this.xmlDoc&&console.log("xml "+this.xmlDoc+" not found!")},getFirstElementByTagName:function(a){return this.xmlDoc?this.xmlDoc.getElementsByTagName(a)[0]:null},getAllTagElements:function(){return this.xmlDoc?this.xmlDoc.getElementsByTagName("*"):null},getStringAttribute:function(a,b,d){return(a=a.getAttribute(b))?a.trim():d},getIntAttribute:function(a,b,d){return(a=this.getStringAttribute(a,b,d))?parseInt(a):d},getFloatAttribute:function(a,b,d){return(a=this.getStringAttribute(a,b,d))?parseFloat(a):
d},getBooleanAttribute:function(a,b,d){return(a=this.getStringAttribute(a,b,d))?"true"==a:d},free:function(){this.parser=this.xmlDoc=null}}}var d=b.document;me={mod:"melonJS",nocache:"",audio:null,video:null,timer:null,input:null,state:null,game:null,entityPool:null,levelDirector:null,XMLParser:null,loadingScreen:null,TMXTileMap:null,debug:{displayFPS:!1,renderHitBox:!1,renderDirty:!1}};me.sys={ua:navigator.userAgent.toLowerCase(),sound:!1,localStorage:"object"==typeof b.localStorage,gyro:b.DeviceMotionEvent!==
c,nativeBase64:"function"==typeof b.atob,fps:60,interpolation:!1,scale:1,useNativeAnimFrame:!1,cacheImage:!1,dirtyRegion:!1,enableWebGL:!1,stopOnAudioError:!0};b.me=me;var f=!1,g=!1,i=!1,h=[];onReady=function(e){g||(g=!0,"complete"===d.readyState?util.domReady():(d.addEventListener&&d.addEventListener("DOMContentLoaded",a,!1),b.addEventListener("load",a,!1)));i?e.call(b,[]):h.push(function(){return e.call(b,[])});return this};b.onReady(function(){if(!f){var a=d.createElement("audio");me.utils.setNocache(d.location.href.match(/\?nocache/));
if(a.canPlayType)me.audio.capabilities.mp3="no"!=a.canPlayType("audio/mpeg")&&""!=a.canPlayType("audio/mpeg"),me.audio.capabilities.ogg="no"!=a.canPlayType('audio/ogg; codecs="vorbis"')&&""!=a.canPlayType('audio/ogg; codecs="vorbis"'),me.audio.capabilities.wav="no"!=a.canPlayType('audio/wav; codecs="1"')&&""!=a.canPlayType('audio/wav; codecs="1"'),me.sys.sound=me.audio.capabilities.mp3||me.audio.capabilities.ogg||me.audio.capabilities.wav;if(-1<me.sys.ua.search("iphone")||-1<me.sys.ua.search("ipod")||
-1<me.sys.ua.search("ipad")||-1<me.sys.ua.search("android"))me.sys.sound=!1;me.timer.init();me.XMLParser=new e;me.loadingScreen=new me.DefaultLoadingScreen;me.state.init();me.entityPool.init();me.levelDirector.reset();f=!0}});var j=!1,k=/xyz/.test(function(){})?/\bparent\b/:/.*/;Object.extend=function(a){function b(){!j&&this.init&&this.init.apply(this,arguments)}var d=this.prototype;j=!0;var e=new this;j=!1;for(var f in a)e[f]="function"==typeof a[f]&&"function"==typeof d[f]&&k.test(a[f])?function(a,
b){return function(){var e=this.parent;this.parent=d[a];var f=b.apply(this,arguments);this.parent=e;return f}}(f,a[f]):a[f];b.prototype=e;b.constructor=b;b.extend=arguments.callee;return b};if("function"!==typeof Object.create)Object.create=function(a){function b(){}b.prototype=a;return new b};if(!Function.bind)Function.prototype.bind=function(){var a=this,b=Array.prototype.slice.call(arguments),d=b.shift();return function(){return a.apply(d,b.concat(Array.prototype.slice.call(arguments)))}};Function.prototype.defer=
function(){var a=this,b=Array.prototype.slice.call(arguments);return window.setTimeout(function(){return a.apply(a,b)},0.01)};if(!Object.defineProperty)Object.defineProperty=function(a,b,d){if(a.__defineGetter__)d.get&&a.__defineGetter__(b,d.get),d.set&&a.__defineSetter__(b,d.set);else throw"melonJS: Object.defineProperty not supported";};String.prototype.trim=function(){return this.replace(/^\s+/,"").replace(/\s+$/,"")};String.prototype.isNumeric=function(){return null!=this&&!isNaN(this)&&""!=this.trim()};
String.prototype.isBoolean=function(){return null!=this&&("true"==this.trim()||"false"==this.trim())};String.prototype.contains=function(a){return-1<this.indexOf(a)};String.prototype.toHex=function(){for(var a="",b=0;b<this.length;)a+=this.charCodeAt(b++).toString(16);return a};Number.prototype.clamp=function(a,b){return this<a?a:this>b?b:this};Number.prototype.random=function(a,b){return~~(Math.random()*(b-a+1))+a};Number.prototype.round=function(){var a=1==arguments.length?this:arguments[0],b=Math.pow(10,
arguments[1]||arguments[0]);return Math.round(a*b)/b};Number.prototype.toHex=function(){return"0123456789ABCDEF".charAt(this-this%16>>4)+"0123456789ABCDEF".charAt(this%16)};Number.prototype.sign=function(){return 0>this?-1:0<this?1:0};var l=function(){var a={},b=[],d,e=[];a.isDirty=!1;a.reset=function(){b=[];e=[];d=me.game.viewport.getRect();a.makeAllDirty()};a.makeDirty=function(d,f,c){if(f)a.isDirty=!0,me.sys.dirtyRegion&&(c?b.push(c.union(d)):d.getRect&&b.push(d.getRect()));d.visible&&e.splice(0,
0,d)};a.makeAllDirty=function(){b=[];b.push(d);a.isDirty=!0};a.remove=function(b){e.splice(e.indexOf(b),1);var d=b.visible;b.visible=!1;a.makeDirty(b,!0);b.visible=d};a.draw=function(a){for(var d=b.length,f;d--,f=b[d];){for(var c=e.length,g;c--,g=e[c];)(!me.sys.dirtyRegion||!g.isEntity||g.overlaps(f))&&g.draw(a,f);me.debug.renderDirty&&f.draw(a,"white")}};a.flush=function(){me.sys.dirtyRegion&&(b=[]);e=[];a.isDirty=!1};return a}();me.game=function(){var a={},b=null,d=[],e=0,f=!1,c=[],g=null;a.viewport=
null;a.HUD=null;a.collisionMap=null;a.currentLevel=null;a.NO_OBJECT=0;a.ENEMY_OBJECT=1;a.COLLECTABLE_OBJECT=2;a.ACTION_OBJECT=3;a.init=function(d,e){if(!f)d=d||me.video.getWidth(),e=e||me.video.getHeight(),a.viewport=new me.Viewport(0,0,d,e),b=me.video.getScreenFrameBuffer(),f=!0};a.reset=function(){g&&clearTimeout(g);g=null;f||a.init();a.removeAll();a.viewport&&a.viewport.reset();null!=a.HUD&&a.add(a.HUD);l.reset()};a.loadTMXLevel=function(b){a.currentLevel=b;a.collisionMap=a.currentLevel.getLayerByName("collision");
(!a.collisionMap||!a.collisionMap.isCollisionMap)&&alert("WARNING : no collision map detected");a.currentLevel.addTo(me.game);if(a.currentLevel.realwidth<a.viewport.getWidth()||a.currentLevel.realheight<a.viewport.getHeight())throw"melonJS: map size should be at least equal to the defined display size";a.viewport.setBounds(a.currentLevel.realwidth,a.currentLevel.realheight);for(var b=a.currentLevel.getObjectGroups(),d=0;d<b.length;d++)for(var e=0;e<b[d].objects.length;e++)a.addEntity(b[d].objects[e],
b[d].z);a.sort()};a.add=function(a,b){a.z=b?b:a.z;d.push(a);a.mouseEvent&&c.push(a);e=d.length};a.addEntity=function(b,d){a.add(me.entityPool.newIstanceOf(b),d)};a.getEntityByName=function(a){for(var b=[],f=e,c;f--,c=d[f];)c.name==a&&b.push(c);return b};a.getEntityByGUID=function(a){for(var b=e,f;b--,f=d[b];)if(f.isEntity&&f.GUID==a)return f;return null};a.addHUD=function(b,d,e,f,c){if(null==a.HUD)a.HUD=new me.HUD_Object(b,d,e,f,c),a.add(a.HUD)};a.disableHUD=function(){if(null!=a.HUD)a.remove(a.HUD),
a.HUD=null};a.mouseEvent=function(a,b){for(var d=c.length;d--&&!c[d].mouseEvent(a,b););};a.update=function(){me.timer.update();for(var b=null,f=e,c;f--,c=d[f];){var b=me.sys.dirtyRegion&&c.isEntity?c.getRect():null,g=c.update();if(c.isEntity)c.visible=a.viewport.isVisible(c.collisionBox);l.makeDirty(c,g,g?b:null)}a.viewport.update(l.isDirty)&&l.makeAllDirty()};a.remove=function(a){if(!a.destroy||a.destroy())a.visible=!1,a.isEntity=!1,l.remove(a),a.mouseEvent&&c.splice(c.indexOf(a),1),g=function(a){a=
d.indexOf(a);if(-1!=a)d.splice(a,1),e=d.length;g=null}.defer(a)};a.removeAll=function(){e=0;d=[];c=[];l.flush()};a.sort=function(){d.sort(function(a,b){return b.z-a.z});c.sort(function(a,b){return a.z-b.z});a.repaint()};a.collide=function(a){for(var b=null,f=e,c;(f--,c=d[f])&&(!(c.visible&&c.collidable&&c.isEntity&&c!=a)||!(b=c.checkCollision(a))););return b};a.repaint=function(){l.makeAllDirty()};a.draw=function(){l.isDirty&&(l.draw(b),a.viewport.draw(b));l.flush()};return a}();me.ScreenObject=Object.extend({visible:!0,
addAsObject:!1,rect:null,init:function(a){this.addAsObject=a;this.visible=!0===a||!1;this.rect=new me.Rect(new me.Vector2d(0,0),0,0)},reset:function(){me.game.reset();if(this.addAsObject)this.visible=!0,this.rect=me.game.viewport.getRect(),me.game.add(this,999);this.onResetEvent.apply(this,arguments);me.game.sort()},getRect:function(){return this.rect},destroy:function(){this.onDestroyEvent.apply(this,arguments);return!0},update:function(){return!1},onUpdateFrame:function(){me.game.update();me.game.draw();
me.video.blitSurface()},draw:function(){},onResetEvent:function(){},onDestroyEvent:function(){}});window.requestAnimFrame=function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(){return-1}}();window.cancelRequestAnimFrame=function(){return window.cancelAnimationFrame||window.webkitCancelRequestAnimationFrame||window.mozCancelRequestAnimationFrame||window.oCancelRequestAnimationFrame||
window.msCancelRequestAnimationFrame||function(){return-1}}();me.state=function(){function a(){if(-1==i&&-1==h){me.timer.reset();if(me.sys.useNativeAnimFrame){h=window.requestAnimFrame(d);if(-1!=h)return;me.sys.useNativeAnimFrame=!1}i=setInterval(q,s)}}function d(){q();window.requestAnimFrame(d)}function e(){-1!=i&&(clearInterval(i),i=-1);-1!=h&&(cancelRequestAnimFrame(h),h=-1)}function f(b){e();k[g]&&(k[g].screen.visible?me.game.remove(k[g].screen):k[g].screen.destroy());g=b;k[g].screen.reset.apply(k[g].screen,
r);q=k[g].screen.onUpdateFrame.bind(k[g].screen);a();o&&o();me.game.repaint()}var c={},g=-1,i=-1,h=-1,k={},j="",l=0,o=null,r=null,q=null,s=null;c.LOADING=0;c.MENU=1;c.READY=2;c.PLAY=3;c.GAMEOVER=4;c.GAME_END=5;c.SCORE=6;c.CREDITS=7;c.SETTINGS=8;c.onPause=null;c.onResume=null;c.init=function(){c.set(c.LOADING,me.loadingScreen);b.addEventListener("blur",function(){if(g!=c.LOADING&&(c.pause(!0),c.onPause))c.onPause()},!1);b.addEventListener("focus",function(){if(g!=c.LOADING){c.resume(!0);if(c.onResume)c.onResume();
me.game.repaint()}},!1);s=~~(1E3/me.sys.fps)};c.pause=function(a){e();a&&me.audio.pauseTrack()};c.resume=function(b){a(g);b&&me.audio.resumeTrack()};c.isRunning=function(){return-1!=i||-1!=h};c.set=function(a,b){k[a]={};k[a].screen=b;k[a].transition=!0};c.current=function(){return k[g].screen};c.transition=function(a,b,d){"fade"==a&&(j=b,l=d)};c.setTransition=function(a,b){k[a].transition=b};c.change=function(a){switch(a){default:r=null,1<arguments.length&&(r=Array.prototype.slice.call(arguments,
1)),l&&k[a].transition?(o=function(){me.game.viewport.fadeOut(j,l)},me.game.viewport.fadeIn(j,l,function(){f(a)})):f.defer(a)}};c.isCurrent=function(a){return g==a};return c}()})(window);
(function(b,c){me.DefaultLoadingScreen=me.ScreenObject.extend({init:function(){this.parent(!0);this.logo1=new me.Font("century gothic",32,"white");this.logo2=new me.Font("century gothic",32,"#89b002");this.logo2.bold();this.invalidate=!1;this.loadPercent=0;me.loader.onProgress=this.onProgressUpdate.bind(this)},onDestroyEvent:function(){this.logo1=this.logo2=null},onProgressUpdate:function(a){this.loadPercent=a;this.invalidate=!0},update:function(){return!0===this.invalidate?(this.invalidate=!1,!0):
!1},draw:function(a){var b=a.canvas.height/2,d=this.logo1.measureText(a,"melon").width,c=d+this.logo2.measureText(a,"JS").width;me.video.clearSurface(a,"black");this.logo1.draw(a,"melon",(a.canvas.width-c)/2,(a.canvas.height+60)/2);this.logo2.draw(a,"JS",(a.canvas.width-c)/2+d,(a.canvas.height+60)/2);b+=40;d=Math.floor(this.loadPercent*a.canvas.width);a.strokeStyle="silver";a.strokeRect(0,b,a.canvas.width,6);a.fillStyle="#89b002";a.fillRect(2,b+2,d-4,2)}});me.loader=function(){function a(){if(k==
j-l){for(var b in i)i[b].isTMX&&(me.levelDirector.addTMXLevel(b),f.onResourceLoaded());f.onload?setTimeout(f.onload,300):alert("no load callback defined")}else setTimeout(a,100)}function e(a,d,e,c){if(b.XMLHttpRequest){var f=new XMLHttpRequest;f.overrideMimeType&&f.overrideMimeType("text/xml")}else f=new ActiveXObject("Microsoft.XMLHTTP");f.open("GET",a.src+me.nocache,!1);f.onerror=c;f.onload=function(){i[a.name]={};i[a.name].xml=f.responseText;i[a.name].isTMX=d;e()};d&&(this.resourceCount+=1,this.tmxCount+=
1);f.send()}function d(a,b,d){var e=new XMLHttpRequest;e.open("GET",a.src+me.nocache,!1);e.responseType="arraybuffer";xmlhttp.onerror=d;e.onload=function(){var d=e.response;if(d){var d=new Uint8Array(d),c=[];h[a.name]=new dataType;for(var f=0;f<d.byteLength;f++)c[f]=String.fromCharCode(d[f]);h[a.name].data=c.join("");b()}};e.send()}var f={},g=[],i={},h={},j=0,k=0,l=0;f.onload=c;f.onProgress=c;f.onResourceLoaded=function(){k++;if(f.onProgress)f.onProgress(f.getLoadProgress())};f.onLoadingError=function(a){throw"melonJS: Failed loading resource "+
a.src;};f.preload=function(b){for(var d=0;d<b.length;d++)j+=f.load(b[d],f.onResourceLoaded.bind(f),f.onLoadingError.bind(f,b[d]));a()};f.load=function(a,b,c){a.name=a.name.toLowerCase();switch(a.type){case "binary":return d(a,b,c),1;case "image":return g.push(a.name),g[a.name]=new Image,g[a.name].onload=b,g[a.name].onerror=c,g[a.name].src=a.src+me.nocache,1;case "tmx":return e(a,!0,b,c),1;case "audio":me.audio.setLoadCallback(b);if(me.audio.isAudioEnable())return me.audio.load(a),1;break;default:throw"melonJS: me.loader.load : unknow or invalide resource type : %s"+
a.type;}return 0};f.getXML=function(a){a=a.toLowerCase();return null!=i?i[a].xml:null};f.getBinary=function(a){a=a.toLowerCase();return null!=h?h[a]:null};f.getImage=function(a){a=a.toLowerCase();if(null!=g[a]){if(!0===me.sys.cacheImage){var b=me.video.createCanvasSurface(g[a].width,g[a].height);b.drawImage(g[a],0,0);return b.canvas}return g[a]}return null};f.getLoadProgress=function(){return k/j};return f}()})(window);
(function(){me.Vector2d=Object.extend({x:0,y:0,init:function(b,c){this.x=b||0;this.y=c||0},set:function(b,c){this.x=b;this.y=c},setZero:function(){this.set(0,0)},setV:function(b){this.x=b.x;this.y=b.y},add:function(b){this.x+=b.x;this.y+=b.y},sub:function(b){this.x-=b.x;this.y-=b.y},scale:function(b){this.x*=b.x;this.y*=b.y},div:function(b){this.x/=b;this.y/=b},abs:function(){if(0>this.x)this.x=-this.x;if(0>this.y)this.y=-this.y},clamp:function(b,c){return new me.Vector2d(this.x.clamp(b,c),this.y.clamp(b,
c))},minV:function(b){this.x=this.x<b.x?this.x:b.x;this.y=this.y<b.y?this.y:b.y},maxV:function(b){this.x=this.x>b.x?this.x:b.x;this.y=this.y>b.y?this.y:b.y},negate:function(){return new me.Vector2d(-this.x,-this.y)},negateSelf:function(){this.x=-this.x;this.y=-this.y},copy:function(b){this.x=b.x;this.y=b.y},length:function(){return Math.sqrt(this.x*this.x+this.y*this.y)},normalize:function(){var b=this.length();if(b<Number.MIN_VALUE)return 0;var c=1/b;this.x*=c;this.y*=c;return b},dotProduct:function(b){return this.x*
b.x+this.y*b.y},distance:function(b){return Math.sqrt((this.x-b.x)*(this.x-b.x)+(this.y-b.y)*(this.y-b.y))},clone:function(){return new me.Vector2d(this.x,this.y)},toString:function(){return"x:"+this.x+"y:"+this.y}});me.Rect=Object.extend({pos:null,colPos:null,left:null,right:null,top:null,bottom:null,width:0,height:0,hWidth:0,hHeight:0,hProp:!1,vProp:!1,init:function(b,c,a){this.pos=b;this.colPos=new me.Vector2d;this.width=c;this.height=a;this.hWidth=~~(c/2);this.hHeight=~~(a/2);Object.defineProperty(this,
"left",{get:function(){return this.pos.x},configurable:!0});Object.defineProperty(this,"right",{get:function(){return this.pos.x+this.width},configurable:!0});Object.defineProperty(this,"top",{get:function(){return this.pos.y},configurable:!0});Object.defineProperty(this,"bottom",{get:function(){return this.pos.y+this.height},configurable:!0})},set:function(b,c,a){this.pos=b;this.width=c;this.height=a;this.hWidth=~~(c/2);this.hHeight=~~(a/2)},getRect:function(){return new me.Rect(this.pos.clone(),
this.width,this.height)},union:function(b){var c=Math.min(this.pos.x,b.pos.x),a=Math.min(this.pos.y,b.pos.y);this.width=Math.ceil(Math.max(this.pos.x+this.width,b.pos.x+b.width)-c);this.height=Math.ceil(Math.max(this.pos.y+this.height,b.pos.y+b.height)-a);this.pos.x=~~c;this.pos.y=~~a;return this},adjustSize:function(b,c,a,e){if(-1!=b&&(this.colPos.x=b,this.width=c,this.hWidth=~~(this.width/2),!this.hProp))Object.defineProperty(this,"left",{get:function(){return this.pos.x+this.colPos.x},configurable:!0}),
Object.defineProperty(this,"right",{get:function(){return this.pos.x+this.colPos.x+this.width},configurable:!0}),this.hProp=!0;if(-1!=a&&(this.colPos.y=a,this.height=e,this.hHeight=~~(this.height/2),!this.vProp))Object.defineProperty(this,"top",{get:function(){return this.pos.y+this.colPos.y},configurable:!0}),Object.defineProperty(this,"bottom",{get:function(){return this.pos.y+this.colPos.y+this.height},configurable:!0}),this.vProp=!0},flipX:function(b){this.colPos.x=b-this.width-this.colPos.x;
this.hWidth=~~(this.width/2)},flipY:function(b){this.colPos.y=b-this.height-this.colPos.y;this.hHeight=~~(this.height/2)},overlaps:function(b){return this.left<b.right&&b.left<this.right&&this.top<b.bottom&&b.top<this.bottom},within:function(b){return b.left<=this.left&&b.right>=this.right&&b.top<=this.top&&b.bottom>=this.bottom},contains:function(b){return b.left>=this.left&&b.right<=this.right&&b.top>=this.top&&b.bottom<=this.bottom},collideVsAABB:function(b){var c=new me.Vector2d(0,0);if(this.overlaps(b)){var a=
this.left+this.hWidth-b.left-b.hWidth,e=this.top+this.hHeight-b.top-b.hHeight;c.x=b.hWidth+this.hWidth-(0>a?-a:a);c.y=b.hHeight+this.hHeight-(0>e?-e:e);c.x<c.y?(c.y=0,c.x=0>a?-c.x:c.x):(c.x=0,c.y=0>e?-c.y:c.y)}return c},draw:function(b,c){b.strokeStyle=c||"red";b.strokeRect(this.left-me.game.viewport.pos.x,this.top-me.game.viewport.pos.y,this.width,this.height)}})})(window);
(function(){var b=Math.min,c=Math.max;me.Viewport=me.Rect.extend({AXIS:{NONE:0,HORIZONTAL:1,VERTICAL:2,BOTH:3},limits:null,target:null,follow_axis:0,_shake:null,_fadeIn:null,_fadeOut:null,_deadwidth:0,_deadheight:0,_limitwidth:0,_limitheight:0,init:function(a,b,d,c,g,i){this.parent(new me.Vector2d(a,b),d-a,c-b);this.last=new me.Vector2d(-1,-1);this.limits=new me.Vector2d(g||this.width,i||this.height);this.target=null;this.follow_axis=this.AXIS.NONE;this._shake={intensity:0,duration:0,axis:this.AXIS.BOTH,
onComplete:null};this._fadeOut={color:0,alpha:0,duration:0,tween:null};this._fadeIn={color:0,alpha:1,duration:0,tween:null};this.setDeadzone(this.width/6,this.height/6)},_followH:function(a){if(a.x-this.pos.x>this._deadwidth)this.pos.x=~~b(a.x-this._deadwidth,this._limitwidth);else if(a.x-this.pos.x<this.deadzone.x)this.pos.x=~~c(a.x-this.deadzone.x,0)},_followV:function(a){if(a.y-this.pos.y>this._deadheight)this.pos.y=~~b(a.y-this._deadheight,this._limitheight);else if(a.y-this.pos.y<this.deadzone.y)this.pos.y=
~~c(a.y-this.deadzone.y,0)},reset:function(a,b){this.pos.x=a||0;this.pos.y=b||0;this.last.set(-1,-1);this.follow_axis=this.target=null},setDeadzone:function(a,b){this.deadzone=new me.Vector2d(~~((this.width-a)/2),~~((this.height-b)/2-0.25*b));this._deadwidth=this.width-this.deadzone.x;this._deadheight=this.height-this.deadzone.y;this.update(!0)},setBounds:function(a,b){this.limits.set(a,b);this._limitwidth=this.limits.x-this.width;this._limitheight=this.limits.y-this.height},follow:function(a,b){if(a instanceof
me.ObjectEntity)this.target=a.pos;else if(a instanceof me.Vector2d)this.target=a;else throw"melonJS: invalid target for viewport.follow";this.follow_axis=b||this.AXIS.BOTH;this.update(!0)},move:function(a,b){var d=~~(this.pos.x+a),c=~~(this.pos.y+b);if(0<=d&&d<=this._limitwidth)this.pos.x=d;if(0<=c&&c<=this._limitheight)this.pos.y=c},update:function(a){if(this.target&&a){switch(this.follow_axis){case this.AXIS.HORIZONTAL:this._followH(this.target,0<this._shake.duration);break;case this.AXIS.VERTICAL:this._followV(this.target,
0<this._shake.duration);break;case this.AXIS.BOTH:this._followH(this.target,0<this._shake.duration),this._followV(this.target,0<this._shake.duration)}a=this.last.x!=this.pos.x||this.last.y!=this.pos.y;this.last.copy(this.pos)}if(0<this._shake.duration)if(this._shake.duration-=me.timer.tick,0>this._shake.duration){if(this._shake.onComplete)this._shake.onComplete()}else{if(this._shake.axis==this.AXIS.BOTH||this._shake.axis==this.AXIS.HORIZONTAL)a=Math.random()*this._shake.intensity,this.pos.x=this.pos.x+
this.width+a<this.limits.x?this.pos.x+~~a:this.pos.x-~~a;if(this._shake.axis==this.AXIS.BOTH||this._shake.axis==this.AXIS.VERTICAL)a=Math.random()*this._shake.intensity,this.pos.y=this.pos.y+this.height+a<this.limits.y?this.pos.y+~~a:this.pos.y-~~a;a=!0}if(null!=this._fadeIn.tween||null!=this._fadeOut.tween)a=!0;return a},shake:function(a,b,d,c){d=d||this.AXIS.BOTH;if(d==this.AXIS.BOTH)if(this.width==this.limits.x)d=this.AXIS.VERTICAL;else if(this.height==this.limits.y)d=this.AXIS.HORIZONTAL;if(!(d==
this.AXIS.HORIZONTAL&&this.width==this.limits.x||d==this.AXIS.VERTICAL&&this.height==this.limits.y))this._shake.intensity=a,this._shake.duration=b,this._shake.axis=d,this._shake.onComplete=c||null},fadeOut:function(a,b,d){this._fadeOut.color=a;this._fadeOut.duration=b||1E3;this._fadeOut.alpha=1;this._fadeOut.tween=(new me.Tween(this._fadeOut)).to({alpha:0},this._fadeOut.duration).onComplete(d||null);this._fadeOut.tween.start()},fadeIn:function(a,b,d){this._fadeIn.color=a;this._fadeIn.duration=b||
1E3;this._fadeIn.alpha=0;this._fadeIn.tween=(new me.Tween(this._fadeIn)).to({alpha:1},this._fadeIn.duration).onComplete(d||null);this._fadeIn.tween.start()},getWidth:function(){return this.width},getHeight:function(){return this.height},focusOn:function(a){this.pos.x=a.x-0.5*this.width;this.pos.y=a.y-0.5*this.height},isVisible:function(a){return a.overlaps(this)},draw:function(a){if(this._fadeIn.tween&&(me.sys.enableWebGL?me.video.clearSurface(a,me.utils.HexToRGB(this._fadeIn.color,this._fadeIn.alpha)):
(a.globalAlpha=this._fadeIn.alpha,me.video.clearSurface(a,me.utils.HexToRGB(this._fadeIn.color)),a.globalAlpha=1),1==this._fadeIn.alpha))this._fadeIn.tween=null;if(this._fadeOut.tween&&(me.sys.enableWebGL?me.video.clearSurface(a,me.utils.HexToRGB(this._fadeOut.color,this._fadeOut.alpha)):(a.globalAlpha=this._fadeOut.alpha,me.video.clearSurface(a,me.utils.HexToRGB(this._fadeOut.color)),a.globalAlpha=1),0==this._fadeOut.alpha))this._fadeOut.tween=null}})})(window);
(function(){var b=Math.min;me.ObjectSettings={name:null,image:null,transparent_color:null,spritewidth:null,spriteheight:null,type:0,collidable:!1};me.entityPool=function(){var a={},b={};a.init=function(){a.add("me.LevelEntity",me.LevelEntity);a.add("me.ObjectEntity",me.ObjectEntity);a.add("me.CollectableEntity",me.CollectableEntity);a.add("me.InvisibleEntity",me.InvisibleEntity)};a.add=function(a,c){b[a.toLowerCase()]=c};a.newIstanceOf=function(a){return!b[a.name.toLowerCase()]?(alert("cannot instance entity of type '"+
a.name+"': Class not found!"),null):new (b[a.name.toLowerCase()])(a.x,a.y,a)};return a}();var c=me.Rect.extend({init:function(a,b,d){this.image=me.loader.getImage(a);if(null==this.image)throw"melonJS: image "+a+" for Parallax Layer not found!";this.parent(new me.Vector2d(0,0),this.image.width,this.image.height);this.baseOffset=0;this.z=d||0;this.scrollspeed=b;this.vp_width=me.game.viewport.width},draw:function(a,c,d){var f=0,g=b(this.width-c,this.vp_width);do a.drawImage(this.image,c,0,g,this.height,
f,d,g,this.height),f+=g,c=0,g=b(this.width,this.vp_width-f);while(f<this.vp_width)}});me.ParallaxBackgroundEntity=me.Rect.extend({init:function(a){this.parent(new me.Vector2d(0,0),0,0);this.name="parallaxBackgroundEntity";this.visible=!0;this.z=a||0;this.vp=me.game.viewport.pos;this.lastx=this.vp.x;this.parallaxLayers=[];this.updated=!0},addLayer:function(a,b,d){var f=this.parallaxLayers.length;this.parallaxLayers.push(new c(a,b,d));if(this.parallaxLayers[f].width>this.width)this.width=this.parallaxLayers[f].width;
if(this.parallaxLayers[f].height>this.height)this.height=this.parallaxLayers[f].height},clearTile:function(){},update:function(){return this.updated},getRect:function(){return new me.Rect(this.vp.clone(),this.width,this.height)},draw:function(a){var b=this.vp.x;if(b>this.lastx)for(var d=0,c;c=this.parallaxLayers[d++];)c.baseOffset=(c.baseOffset+c.scrollspeed*me.timer.tick)%c.width,c.draw(a,~~c.baseOffset,0),this.lastx=b,this.updated=!0;else if(b<this.lastx)for(d=0;c=this.parallaxLayers[d++];)c.baseOffset=
(c.width+(c.baseOffset-c.scrollspeed*me.timer.tick))%c.width,c.draw(a,~~c.baseOffset,0),this.lastx=b,this.updated=!0;else for(d=0;c=this.parallaxLayers[d++];)c.draw(a,~~c.baseOffset,0),this.lastx=b,this.updated=!1}});me.SpriteObject=me.Rect.extend({scale:null,scaleFlag:!1,lastflipX:!1,lastflipY:!1,z:0,offset:null,autodestroy:!0,visible:!0,image:null,collisionBox:null,flickering:!1,flickerTimer:-1,flickercb:null,flickerState:!1,vp:null,init:function(a,b,d,c,g){this.parent(new me.Vector2d(a,b),c||d.width,
g||d.height);this.image=d;this.scale=new me.Vector2d(1,1);this.collisionBox=new me.Rect(this.pos,this.width,this.height);this.vp=me.game.viewport;this.offset=new me.Vector2d(0,0);this.spritecount=new me.Vector2d(~~(this.image.width/this.width),~~(this.image.height/this.height))},setTransparency:function(a){a="#"==a.charAt(0)?a.substring(1,7):a;this.image=me.video.applyRGBFilter(this.image,"transparent",a.toUpperCase()).canvas},isFlickering:function(){return this.flickering},flicker:function(a,b){this.flickerTimer=
a;if(0>this.flickerTimer)this.flickering=!1,this.flickercb=null;else if(!this.flickering)this.flickercb=b,this.flickering=!0},flipX:function(a){if(a!=this.lastflipX)this.lastflipX=a,this.scale.x=-this.scale.x,this.scaleFlag=1!=this.scale.x||1!=this.scale.y,this.collisionBox.flipX(this.width)},flipY:function(a){if(a!=this.lastflipY)this.lastflipY=a,this.scale.y=-this.scale.y,this.scaleFlag=1!=this.scale.x||1!=this.scale.y,this.collisionBox.flipY(this.height)},resize:function(a){if(0<a)this.scale.x=
0>this.scale.x?-a:a,this.scale.y=0>this.scale.y?-a:a,this.scaleFlag=1!=this.scale.x||1!=this.scale.y},update:function(){return this.flickering?(this.flickerTimer-=me.timer.tick,0>this.flickerTimer&&(this.flickercb&&this.flickercb(),this.flicker(-1)),!0):!1},draw:function(a){if(this.flickering&&(this.flickerState=!this.flickerState,!this.flickerState))return;var b=~~(this.pos.x-this.vp.pos.x),d=~~(this.pos.y-this.vp.pos.y);this.scaleFlag&&(a.translate(b+this.hWidth,d+this.hHeight),a.scale(this.scale.x,
this.scale.y),a.translate(-this.hWidth,-this.hHeight),b=d=0);a.drawImage(this.image,this.offset.x,this.offset.y,this.width,this.height,b,d,this.width,this.height);this.scaleFlag&&a.setTransform(1,0,0,1,0,0);me.debug.renderHitBox&&(this.parent(a,"blue"),this.collisionBox.draw(a,"red"))},destroy:function(){if(this.autodestroy)this.onDestroyEvent();return this.autodestroy},onDestroyEvent:function(){}});me.AnimationSheet=me.SpriteObject.extend({fpscount:0,animationspeed:0,init:function(a,b,d,c,g){this.anim=
[];this.current=this.resetAnim=null;this.parent(a,b,d,c,g);if(1==this.spritecount.x*this.spritecount.y)this.setCurrentSprite=function(){};this.animationspeed=me.sys.fps/10;this.addAnimation("default",null);this.setCurrentAnimation("default")},addAnimation:function(a,b){this.anim[a]={name:null,frame:[],idx:0,length:0};if(null==b)for(var b=[],d=0;d<this.spritecount.x;d++)b[d]=d;for(var c=0,d=0;d<b.length;d++)this.anim[a].frame[c]=new me.Vector2d(this.width*(b[d]%this.spritecount.x),this.height*~~(b[d]/
this.spritecount.x)),c++;this.anim[a].name=a;this.anim[a].length=this.anim[a].frame.length},setCurrentAnimation:function(a,b){this.current=this.anim[a];this.resetAnim=b||null;this.offset=this.current.frame[this.current.idx]},isCurrentAnimation:function(a){return this.current.name==a},setCurrentSprite:function(a){this.current.idx=a;this.offset=this.current.frame[a];0==this.current.idx&&this.resetAnim&&("string"==typeof this.resetAnim?this.setCurrentAnimation(this.resetAnim):"function"==typeof this.resetAnim&&
this.resetAnim())},update:function(){this.parent();return this.visible&&this.fpscount++>this.animationspeed?(this.setCurrentSprite(++this.current.idx%this.current.length),this.fpscount=0,!0):!1}});me.ObjectEntity=me.AnimationSheet.extend({GUID:null,type:0,collidable:!1,init:function(a,b,d){this.parent(a,b,"string"==typeof d.image?me.loader.getImage(d.image):d.image,d.spritewidth,d.spriteheight);d.transparent_color&&this.setTransparency(d.transparent_color);this.GUID=me.utils.createGUID();this.name=
d.name;this.pos.set(a,me.game.currentLevel?b+me.game.currentLevel.tileheight-this.height:b);this.vel=new me.Vector2d;this.accel=new me.Vector2d;this.friction=new me.Vector2d;this.maxVel=new me.Vector2d(1E3,1E3);this.gravity=0.98;this.alive=this.isEntity=!0;this.falling=!1;this.jumping=!0;this.slopeY=0;this.onladder=this.onslope=!1;this.collidable=d.collidable||!1;this.type=d.type||0;this.collisionMap=me.game.collisionMap;this.canBreakTile=!1;this.onTileBreak=null},updateColRect:function(a,b,d,c){this.collisionBox.adjustSize(a,
b,d,c)},checkCollision:function(a){var b=this.collisionBox.collideVsAABB(a.collisionBox);return 0!=b.x||0!=b.y?(this.onCollision(b,a),b.type=this.type,b.obj=this,b):null},onCollision:function(){this.collidable&&this.type==me.game.COLLECTABLE_OBJECT&&me.game.remove(this)},setVelocity:function(a,b){this.accel.x=0!=a?a:this.accel.x;this.accel.y=0!=a?b:this.accel.y;this.setMaxVelocity(a,b)},setMaxVelocity:function(a,b){this.maxVel.x=a;this.maxVel.y=b},setFriction:function(a,b){this.friction.x=a||0;this.friction.y=
b||0},doWalk:function(a){this.flipX(a);this.vel.x+=a?-this.accel.x*me.timer.tick:this.accel.x*me.timer.tick},doClimb:function(a){return this.onladder?(this.vel.y=a?-this.accel.x*me.timer.tick:this.accel.x*me.timer.tick,!0):!1},doJump:function(){return!this.jumping&&!this.falling?(this.vel.y=-this.maxVel.y*me.timer.tick,this.jumping=!0):!1},forceJump:function(){this.jumping=this.falling=!1;this.doJump()},distanceTo:function(a){var b=this.pos.x+(this.width>>1)-(a.pos.x+(a.width>>1)),a=this.pos.y+(this.height>>
1)-(a.pos.y+(a.height>>1));return Math.sqrt(b*b+a*a)},checkSlope:function(a,b){this.pos.y=a.pos.y-this.height;this.slopeY=b?a.height-(this.collisionBox.right+this.vel.x-a.pos.x):this.collisionBox.left+this.vel.x-a.pos.x;this.vel.y=0;this.pos.y+=this.slopeY.clamp(0,a.height)},computeVelocity:function(a){if(this.gravity)a.y+=!this.onladder?this.gravity*me.timer.tick:0,this.jumping=(this.falling=0<a.y)?!1:this.jumping;if(this.friction.x)a.x=me.utils.applyFriction(a.x,this.friction.x);if(this.friction.y)a.y=
me.utils.applyFriction(a.y,this.friction.y);if(0!=a.y)a.y=a.y.clamp(-this.maxVel.y,this.maxVel.y);if(0!=a.x)a.x=a.x.clamp(-this.maxVel.x,this.maxVel.x);return a},updateMovement:function(){this.vel=this.computeVelocity(this.vel);var a=this.collisionMap.checkCollision(this.collisionBox,this.vel);this.onladder=a.xprop.isLadder;this.onslope=a.yprop.isSlope||a.xprop.isSlope;if(a.y)if(0<a.y)if(a.yprop.isSolid||a.yprop.isPlatform&&~~this.pos.y+this.height<=a.ytile.pos.y)this.pos.y=~~this.pos.y,this.vel.y=
this.falling?a.ytile.pos.y-this.pos.y-this.height:0,this.falling=!1;else if(a.yprop.isSlope&&!this.jumping)this.checkSlope(a.ytile,a.yprop.isLeftSlope),this.falling=!1;else{if(a.yprop.isBreakable)if(this.canBreakTile){if(me.game.currentLevel.clearTile(a.ytile.row,a.ytile.col),this.onTileBreak)this.onTileBreak()}else this.pos.y=~~this.pos.y,this.vel.y=this.falling?a.ytile.pos.y-this.pos.y-this.height:0,this.falling=!1}else if(0>a.y&&!a.yprop.isPlatform&&!a.yprop.isLadder)this.falling=!0,this.vel.y=
0;if(a.x)if(a.xprop.isSlope&&!this.jumping)this.checkSlope(a.xtile,a.xprop.isLeftSlope),this.falling=!1;else if(!a.xprop.isPlatform&&!a.xprop.isLadder)if(a.xprop.isBreakable&&this.canBreakTile){if(me.game.currentLevel.clearTile(a.xtile.row,a.xtile.col),this.onTileBreak)this.onTileBreak()}else this.vel.x=0;this.pos.add(this.vel);return a}});me.CollectableEntity=me.ObjectEntity.extend({init:function(a,b,d){this.parent(a,b,d);this.collidable=!0;this.type=me.game.COLLECTABLE_OBJECT}});me.InvisibleEntity=
me.Rect.extend({z:0,collisionBox:null,init:function(a,b,d){this.parent(new me.Vector2d(a,b),d.width,d.height);this.collisionBox=new me.Rect(this.pos,d.width,d.height);this.isEntity=this.collidable=this.visible=!0},updateColRect:function(a,b,d,c){this.collisionBox.adjustSize(a,b,d,c)},checkCollision:function(a){var b=this.collisionBox.collideVsAABB(a.collisionBox);return 0!=b.x||0!=b.y?(this.onCollision(b,a),b.type=this.type,b):null},onCollision:function(){this.collidable&&this.type==me.game.COLLECTABLE_OBJECT&&
me.game.remove(this)},destroy:function(){this.onDestroyEvent();return!0},onDestroyEvent:function(){},update:function(){return!1},draw:function(a){if(me.debug.renderHitBox)a.strokeStyle="blue",a.strokeRect(this.pos.x-me.game.viewport.pos.x,this.pos.y-me.game.viewport.pos.y,this.width,this.height),this.collisionBox.draw(a)}});me.LevelEntity=me.InvisibleEntity.extend({init:function(a,b,d){this.parent(a,b,d);this.nextlevel=d.to;this.fade=d.fade;this.duration=d.duration;this.fading=!1;this.gotolevel=d.to},
onFadeComplete:function(){me.levelDirector.loadLevel(this.gotolevel);me.game.viewport.fadeOut(this.fade,this.duration)},goTo:function(a){this.gotolevel=a||this.nextlevel;if(this.fade&&this.duration){if(!this.fading)this.fading=!0,me.game.viewport.fadeIn(this.fade,this.duration,this.onFadeComplete.bind(this))}else me.levelDirector.loadLevel(this.gotolevel)},onCollision:function(){this.goTo()}})})(window);
(function(){me.Font=Object.extend({ALIGN:{LEFT:"left",CENTER:"center",RIGHT:"right"},font:null,height:null,color:null,align:null,init:function(b,c,a,e){this.set(b,c,a,e)},bold:function(){this.font="bold "+this.font},italic:function(){this.font="italic "+this.font},set:function(b,c,a,e){this.font=""+c+"px "+b;this.height=c;this.color=a;this.align=e||"top"},getRect:function(){return new me.Rect(new Vector2d(0,0),0,0)},measureText:function(b,c){b.font=this.font;b.fillStyle=this.color;b.textBaseLine=
this.align;var a=b.measureText(c);a.height=this.height;return a},draw:function(b,c,a,e){b.font=this.font;b.fillStyle=this.color;b.textBaseLine=this.align;b.fillText(c,~~a,~~e)}});me.BitmapFont=me.Font.extend({size:null,sSize:null,firstChar:32,charCount:0,init:function(b,c,a,e){this.parent(b,null,null);this.size=new me.Vector2d;this.sSize=new me.Vector2d;this.firstChar=e||32;this.loadFontMetrics(b,c);this.align=this.ALIGN.RIGHT;a&&this.resize(a)},loadFontMetrics:function(b,c){this.font=me.loader.getImage(b);
this.size.x=c.x||c;this.size.y=c.y||this.font.height;this.sSize.copy(this.size);this.charCount=~~(this.font.width/this.size.x)},set:function(b,c){this.align=b;c&&this.resize(c)},resize:function(b){this.sSize.copy(this.size);this.sSize.x*=b;this.sSize.y*=b},measureText:function(b){return{width:b.length*this.sSize.x,height:this.sSize.y}},draw:function(b,c,a,e){"string"!=typeof c&&(c=c.toString());this.align==this.ALIGN.RIGHT&&(a-=c.length*this.sSize.x);for(var d=0;d<c.length;d++){var f=c.charCodeAt(d)-
this.firstChar;b.drawImage(this.font,this.size.x*(f%this.charCount),this.size.y*~~(f/this.charCount),this.size.x,this.size.y,~~a,~~e,this.sSize.x,this.sSize.y);a+=this.sSize.x}}})})(window);
(function(){me.GUI_Object=me.SpriteObject.extend({isClickable:!0,updated:!1,init:function(b,c,a){this.parent(b,c,"string"==typeof a.image?me.loader.getImage(a.image):a.image,a.spritewidth,a.spriteheight)},update:function(){return this.updated?(this.updated=!1,!0):!1},clicked:function(){return!0},mouseEvent:function(b,c){if(b>this.left&&b<this.right&&c>this.top&&c<this.bottom&&this.isClickable)this.updated=this.clicked();return this.updated}})})(window);
(function(b,c){me.HUD_Item=Object.extend({init:function(a,b,d){this.pos=new me.Vector2d(a||0,b||0);this.visible=!0;this.defaultvalue=d||0;this.value=d||0;this.updated=!0},reset:function(){this.set(this.defaultvalue)},set:function(a){this.value=a;return this.updated=!0},update:function(a){return this.set(this.value+a)},draw:function(){}});me.HUD_Object=me.Rect.extend({init:function(a,b,d,c,g){this.parent(new me.Vector2d(a||0,b||0),d||me.video.getWidth(),c||me.video.getHeight());this.bgcolor=g;this.HUDItems=
{};this.HUDobj=[];this.objCount=0;this.HUD_invalidated=this.visible=!0;this.HUDCanvasSurface=me.video.createCanvasSurface(this.width,this.height);this.z=999},addItem:function(a,b){this.HUDItems[a]=b;this.HUDobj.push(this.HUDItems[a]);this.objCount++;this.HUD_invalidated=!0},setItemValue:function(a,b){if(this.HUDItems[a]&&!0==this.HUDItems[a].set(b))this.HUD_invalidated=!0},updateItemValue:function(a,b){if(this.HUDItems[a]&&!0==this.HUDItems[a].update(b))this.HUD_invalidated=!0},getItemValue:function(a){return this.HUDItems[a]?
this.HUDItems[a].value:0},update:function(){return this.HUD_invalidated},reset:function(a){a!=c?(this.HUDItems[a]&&this.HUDItems[a].reset(),this.HUD_invalidated=!0):this.resetAll()},resetAll:function(){for(var a=this.objCount,b;a--,b=this.HUDobj[a];)b.reset();this.HUD_invalidated=!0},getRect:function(){p=this.pos.clone();p.add(me.game.viewport.pos);return new me.Rect(p,this.width,this.height)},draw:function(a){if(this.HUD_invalidated){this.bgcolor?me.video.clearSurface(this.HUDCanvasSurface,this.bgcolor):
this.HUDCanvasSurface.canvas.width=this.HUDCanvasSurface.canvas.width;for(var b=this.objCount,d;b--,d=this.HUDobj[b];)if(d.visible&&(d.draw(this.HUDCanvasSurface,0,0),d.updated))d.updated=!1}a.drawImage(this.HUDCanvasSurface.canvas,this.pos.x,this.pos.y);this.HUD_invalidated=!1}})})(window);
(function(){me.audio=function(){function b(){var a=0;if(me.sys.sound){if(-1!=i.search(/mp3/i)&&d.capabilities.mp3)return g[a];if(-1!=i.search(/ogg/i)&&d.capabilities.ogg||-1!=i.search(/wav/i)&&d.capabilities.wav)return g[++a];l=!1;return-1}l=!1}function c(a){for(var a=f[a],b=0,d;d=a[b++];)if(d.ended||!d.currentTime)return d.currentTime=m,d;a[0].pause();a[0].currentTime=m;return a[0]}function a(a,b,d){var f=c(a.toLowerCase());f.loop=b||!1;f.play();d&&!b&&f.addEventListener("ended",function(a){f.removeEventListener("ended",
arguments.callee,!1);d()},!1)}function e(a,b,d){d&&!b&&setTimeout(d,2E3)}var d={},f=[],g=["mp3","ogg","wav"],i=null,h=-1,j=null,k=null,l=!0,m=0,n=0;d.capabilities={mp3:!1,ogg:!1,ma4:!1,wav:!1};d.init=function(c){i=c?new String(c):new String("mp3");h=b();d.play=l?a:e;return l};d.setLoadCallback=function(a){j=a};d.isAudioEnable=function(){return l};d.enable=function(){l=me.sys.sound;d.play=l?a:e};d.disable=function(){l=!1;d.play=e};d.load=function(a){if(-1==h)return 0;var b=new Audio(a.src+a.name+"."+
h+me.nocache);b.preload="auto";b.addEventListener("canplaythrough",function(b){this.removeEventListener("canplaythrough",arguments.callee,!1);var d=a.name,c=a.channel;n=0;if(1<c)for(var g=f[d][0],e=1;e<c;e++){var i=g.cloneNode(!0);if(0==i.currentSrc.length)i.src=g.src;f[d][e]=i;f[d][e].load()}j&&j()},!1);b.addEventListener("error",function(){var b=a.name;if(3<n++)if(b="melonJS: failed loading "+b+"."+h,!1===me.sys.stopOnAudioError)me.audio.disable(),j&&j(),console.log(b+", disabling audio");else throw b;
else f[b][0].load()},!1);b.src=a.src+a.name+"."+h+me.nocache;b.load();f[a.name]=[b];return 1};d.stop=function(a){if(l)for(var a=f[a.toLowerCase()],b=a.length;b--;)a[b].pause(),a[b].currentTime=m};d.pause=function(a){if(l)for(var a=f[a.toLowerCase()],b=a.length;b--;)a[b].pause()};d.playTrack=function(a){if(l&&(null!=k&&d.stopTrack(),k=c(a.toLowerCase())))k.loop=!0,k.play()};d.stopTrack=function(){l&&k&&(k.pause(),k=null)};d.pauseTrack=function(){l&&k&&k.pause()};d.resumeTrack=function(){l&&k&&k.play()};
return d}()})(window);
(function(){me.timer=function(){var b={},c=null,a=!1,e=0,d=0,f=0,g=0,i=0,h=Math.ceil(1E3/me.sys.fps),j=1.25*(1E3/me.sys.fps);b.tick=1;b.init=function(){c=document.getElementById("framecounter");a=null!==c;b.reset()};b.reset=function(){g=f=(new Date).getTime();e=d=0};b.getTime=function(){return g};b.update=function(){f=g;g=(new Date).getTime();i=g-f;if(a&&(e++,d+=i,0==e%10)){var k=(~~(1E3*e/d)).clamp(0,me.sys.fps);c.replaceChild(document.createTextNode("("+k+"/"+me.sys.fps+" fps)"),c.firstChild);e=
d=0}b.tick=i>j&&me.sys.interpolation?i/h:1};return b}();me.video=function(){var b={},c=null,a=null,e=null,d=null,f=null,g=!1,i=0,h=0;b.init=function(j,k,l,m,n){g=m||!1;me.sys.scale=!0===g?n||1:1;i=k*me.sys.scale;h=l*me.sys.scale;f=document.getElementById(j);c=document.createElement("canvas");c.setAttribute("width",i+"px");c.setAttribute("height",h+"px");c.setAttribute("border","0px solid black");f.appendChild(c);if(me.sys.enableWebGL&&window.WebGLRenderingContext)try{WebGL2D.enable(c),a=c.getContext("webgl-2d"),
me.sys.cacheImage=!0}catch(t){a=null}if(null==a){me.sys.enableWebGL=!1;if(!c.getContext)return!1;a=c.getContext("2d")}g?(d=b.createCanvasSurface(k,l),e=d.canvas):(d=a,e=a.canvas);return!0};b.getWrapper=function(){return f};b.getWidth=function(){return e.width};b.getHeight=function(){return e.height};b.createCanvasSurface=function(a,b){var d=document.createElement("canvas");d.width=a||e.width;d.height=b||e.height;return d.getContext("2d")};b.getScreenCanvas=function(){return c};b.getScreenFrameBuffer=
function(){return d};b.updateDisplaySize=function(a){if(g)me.sys.scale=a?a:document.getElementById("screen size").value,i=e.width*me.sys.scale,h=e.height*me.sys.scale,c.width=i,c.height=h};b.clearSurface=function(a,b){a.fillStyle=b;a.fillRect(0,0,a.canvas.width,a.canvas.height)};b.scale=function(a,b){a.translate(-(a.canvas.width*b-a.canvas.width>>1),-(a.canvas.height*b-a.canvas.height>>1));a.scale(b,b)};b.setAlpha=function(a,b){a.globalCompositeOperation=b?"source-over":"copy"};b.blitSurface=function(){b.blitSurface=
g?function(){a.drawImage(e,0,0,e.width,e.height,0,0,i,h)}:function(){};b.blitSurface()};b.applyRGBFilter=function(a,d,c){var f=b.createCanvasSurface(a.width,a.height),a=me.utils.getPixels(a),g=a.data;switch(d){case "b&w":for(var d=0,e=g.length;d<e;d+=4)c=3*g[d]+4*g[d+1]+g[d+2]>>>3,g[d]=c,g[d+1]=c,g[d+2]=c;break;case "brightness":c=Math.abs(c).clamp(0,1);d=0;for(e=g.length;d<e;d+=4)g[d]*=c,g[d+1]*=c,g[d+2]*=c;break;case "transparent":d=0;for(e=g.length;d<e;d+=4)me.utils.RGBToHex(g[d],g[d+1],g[d+2])===
c&&(g[d+3]=0);break;default:return null}f.putImageData(a,0,0);return f};return b}()})(window);
(function(b){me.input=function(){function c(a){a.stopPropagation();a.preventDefault&&a.preventDefault();a.returnValue=!1;a.cancelBubble=!0}function a(a){var b=i[a.keyCode||a.which];return b?(k[b]||(h[b]=!0,k[b]=j[b]),c(a),!1):!0}function e(a){var b=i[a.keyCode||a.which];return b?(h[b]=!1,k[b]=!1,c(a),!1):!0}function d(a){var b=me.video.getScreenCanvas();l(a.clientX+document.body.scrollLeft+document.documentElement.scrollLeft-~~b.offsetLeft,a.clientY+document.body.scrollTop+document.documentElement.scrollTop-
~~b.offsetTop+1)}function f(){}var g={},i=[],h=[],j=[],k=[],l=null,m=!1;g.KEY={LEFT:37,UP:38,RIGHT:39,DOWN:40,ENTER:13,SHIFT:16,CTRL:17,ALT:18,PAUSE:19,ESC:27,SPACE:32,NUM0:48,NUM1:49,NUM2:50,NUM3:51,NUM4:52,NUM5:53,NUM6:54,NUM7:55,NUM8:56,NUM9:57,A:65,B:66,C:67,D:68,E:69,F:70,G:71,H:72,I:73,J:74,K:75,L:76,M:77,N:78,O:79,P:80,Q:81,R:82,S:83,T:84,U:85,V:86,W:87,X:88,Y:89,Z:90};g.isKeyPressed=function(a){return h[a]?(j[a]&&(k[a]=!0,h[a]=!1),!0):!1};g.keyStatus=function(a){return!0===k[a]?!0:h[a]};g.bindKey=
function(d,c,f){m||(m||(b.addEventListener("keydown",a,!1),b.addEventListener("keyup",e,!1)),m=!0);i[d]=c;j[c]=f?f:!1;k[c]=!1};g.unbindKey=function(a){h[i[a]]=!1;j[i[a]]=!1;i[a]=null};g.enableMouseEvent=function(a,b){a?(me.video.getScreenCanvas().addEventListener("click",d,!1),l=b||me.game.mouseEvent.bind(me.game)):me.video.getScreenCanvas().removeEventListener("click",d,!1)};g.enableGyroscopicEvent=function(a){if(b.sys.gyro)b.ondevicemotion=a?f:null};return g}()})(window);
(function(b){var c=function(){return{decode:function(a){a=a.replace(/[^A-Za-z0-9\+\/\=]/g,"");if(me.sys.nativeBase64)return b.atob(a);for(var c=[],d,f,g,i,h,j=0;j<a.length;)d="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(j++)),f="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(j++)),i="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(j++)),h="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(j++)),
d=d<<2|f>>4,f=(f&15)<<4|i>>2,g=(i&3)<<6|h,c.push(String.fromCharCode(d)),64!=i&&c.push(String.fromCharCode(f)),64!=h&&c.push(String.fromCharCode(g));return c=c.join("")}}}();me.utils=function(){var a={},b={},d="",f=0;a.decodeBase64=function(a){return c.decode(a)};a.decodeBase64AsArray=function(a,b){var b=b||1,d=c.decode(a),f=[],e,l,m;for(e=0,m=d.length/b;e<m;e++){f[e]=0;for(l=b-1;0<=l;--l)f[e]+=d.charCodeAt(e*b+l)<<(l<<3)}return f};a.decodeCSV=function(a,b){for(var a=a.trim().split("\n"),d=[],c=0;c<
a.length;c++){entries=a[c].split(",",b);for(var f=0;f<entries.length;f++)d.push(+entries[f])}return d};a.setNocache=function(a){me.nocache=a?"?"+parseInt(1E7*Math.random()):""};a.HexToRGB=function(a,d){a="#"==a.charAt(0)?a.substring(1,7):a;null==b[a]&&(b[a]=parseInt(a.substring(0,2),16)+","+parseInt(a.substring(2,4),16)+","+parseInt(a.substring(4,6),16));return(d?"rgba(":"rgb(")+b[a]+(d?","+d+")":")")};a.RGBToHex=function(a,b,d){return a.toHex()+b.toHex()+d.toHex()};a.getPixels=function(a){if(a instanceof
HTMLImageElement){var b=me.video.createCanvasSurface(a.width,a.height);b.drawImage(a,0,0);return b.getImageData(0,0,a.width,a.height)}return a.getContext("2d").getImageData(0,0,a.width,a.height)};a.resetGUID=function(a){d=a.toUpperCase().toHex();f=0};a.createGUID=function(){return d+"-"+f++};a.applyFriction=function(a,b){return 0>a+b?a+b*me.timer.tick:0<a-b?a-b*me.timer.tick:0};return a}()})(window);
(function(b,c){function a(a){this.defaultvalue=a||0;this.value=a||0;this.updated=!0}a.prototype.reset=function(){this.set(this.defaultvalue)};a.prototype.update=function(a){return this.set(this.value+a)};a.prototype.set=function(a){this.value=a;return this.updated=!0};me.gamestat=function(){var b={},d={},f=[],g=0;b.add=function(b,c){d[b]=new a(c);f.push(d[b]);g++};b.updateValue=function(a,b){d[a]&&d[a].update(b)};b.setValue=function(a,b){d[a]&&d[a].set(b)};b.getItemValue=function(a){return d[a]?d[a].value:
0};b.reset=function(a){a!=c?d[a]&&d[a].reset():b.resetAll()};b.resetAll=function(){for(var a=g,b;a--,b=f[a];)b.reset()};return b}()})(window);
(function(b,c){var a=/^.*(\\|\/|\:)/,e=/\.[^\.]*$/;me.LevelConstants={COLLISION_MAP:"collision",PARALLAX_MAP:"parallax"};me.Tile=me.Rect.extend({init:function(a,b,c,e,h){this.parent(new me.Vector2d(a*c,b*e),c,e);this.tileId=h;this.row=a;this.col=b}});me.Tileset=Object.extend({init:function(b,c,g,i,h,j){this.name=b;this.tilewidth=c;this.tileheight=g;this.spacing=i;this.margin=h;(this.image=j?me.loader.getImage(j.replace(a,"").replace(e,"")):null)||console.log("melonJS: '"+j+"' file for tileset '"+
this.name+"' not found!");this.type={SOLID:"solid",PLATFORM:"platform",L_SLOPE:"lslope",R_SLOPE:"rslope",LADDER:"ladder",BREAKABLE:"breakable"};this.TileProperties=[];if(this.image)this.hTileCount=~~((this.image.width-this.margin)/(this.tilewidth+this.spacing)),this.vTileCount=~~((this.image.height-this.margin)/(this.tileheight+this.spacing))},getPropertyList:function(){return{isCollidable:!1,isSolid:!1,isPlatform:!1,isSlope:!1,isLeftSlope:!1,isRightSlope:!1,isLadder:!1,isBreakable:!1}},getTileProperties:function(a){return this.TileProperties[a]},
isTileCollidable:function(a){return this.TileProperties[a].isCollidable},getTileImage:function(a){var b=me.video.createCanvasSurface(this.tilewidth,this.tileheight);this.drawTile(b,0,0,a);return b.canvas},drawTile:function(a,b,c,e,h,j){var k=this.margin+(this.spacing+this.tilewidth)*(e%this.hTileCount),e=this.margin+(this.spacing+this.tileheight)*~~(e/this.hTileCount);if(h||j)h=0==h?1:-1,j=0==j?1:-1,a.scale(h,j),b=b*h-(0>h?this.tilewidth:0),c=c*j-(0>j?this.tileheight:0);a.drawImage(this.image,k,e,
this.tilewidth,this.tileheight,b,c,this.tilewidth,this.tileheight);(h||j)&&a.setTransform(1,0,0,1,0,0)}});CollisionTiledLayer=Object.extend({init:function(a,b){this.realwidth=a;this.realheight=b;this.isCollisionMap=!0},checkCollision:function(a,b){var c=0>b.x?a.left+b.x:a.right+b.x,e=0>b.y?a.top+b.y:a.bottom+b.y,h={x:0,y:0,xprop:{},yprop:{}};if(0>=c||c>=this.realwidth)h.x=b.x;if(0>=e||e>=this.realheight)h.y=b.y;return h}});me.TiledLayer=Object.extend({init:function(a,b,c,e,h,j){this.width=a;this.height=
b;this.tilewidth=c;this.tileheight=e;this.realwidth=this.width*this.tilewidth;this.realheight=this.height*this.tileheight;this.z=j;this.name=null;this.visible=!1;this.layerData=null;this.xLUT={};this.yLUT={};this.tileset=(this.tilesets=h)?this.tilesets.getTilesetByIndex(0):null},initArray:function(a){this.layerData=[];for(var b=0;b<this.width+1;b++){this.layerData[b]=[];for(var c=0;c<this.height+1;c++)this.layerData[b][c]=null}if(a){for(b=0;b<this.width*this.tilewidth;b++)this.xLUT[b]=~~(b/this.tilewidth);
for(c=0;c<this.height*this.tileheight;c++)this.yLUT[c]=~~(c/this.tileheight)}},getTileId:function(a,b){var c=this.layerData[this.xLUT[~~a]][this.yLUT[~~b]];return c?c.tileId:null},getTile:function(a,b){return this.layerData[this.xLUT[~~a]][this.yLUT[~~b]]},setTile:function(a,b,c){this.layerData[a][b]=new me.Tile(a,b,this.tilewidth,this.tileheight,c)},clearTile:function(a,b){this.layerData[a][b]=null},checkCollision:function(a,b){var e=0>b.x?a.left+b.x:a.right+b.x,i=0>b.y?a.top+b.y:a.bottom+b.y,h=
{x:0,xtile:c,xprop:{},y:0,ytile:c,yprop:{}};if(0>=e||e>=this.realwidth)h.x=b.x;else if(h.xtile=this.getTile(e,a.bottom-1),h.xtile&&this.tileset.isTileCollidable(h.xtile.tileId))h.x=b.x,h.xprop=this.tileset.getTileProperties(h.xtile.tileId);else if(h.xtile=this.getTile(e,a.top),h.xtile&&this.tileset.isTileCollidable(h.xtile.tileId))h.x=b.x,h.xprop=this.tileset.getTileProperties(h.xtile.tileId);h.ytile=this.getTile(0>b.x?a.left:a.right,i);if(h.ytile&&this.tileset.isTileCollidable(h.ytile.tileId))h.y=
b.y||1,h.yprop=this.tileset.getTileProperties(h.ytile.tileId);else if(h.ytile=this.getTile(0>b.x?a.right:a.left,i),h.ytile&&this.tileset.isTileCollidable(h.ytile.tileId))h.y=b.y||1,h.yprop=this.tileset.getTileProperties(h.ytile.tileId);return h},update:function(){return!1}});me.TileMap=Object.extend({init:function(a,b){this.pos=new me.Vector2d(a,b);this.height=this.width=this.z=0;this.realheight=this.realwidth=-1;this.tileheight=this.tilewidth=0;this.tilesets=null;this.mapLayers=[];this.objectGroups=
[];this.initialized=!1},reset:function(){this.tilesets=null;this.mapLayers=[];this.objectGroups=[];this.initialized=!1},getObjectGroupByName:function(a){return this.objectGroups[a]},getObjectGroups:function(){return this.objectGroups},getLayerByName:function(a){for(var b=null,a=a.trim().toLowerCase(),c=this.mapLayers.length;c--;)if(this.mapLayers[c].name.toLowerCase().contains(a)){b=this.mapLayers[c];break}a.toLowerCase().contains(me.LevelConstants.COLLISION_MAP)&&null==b&&(b=new CollisionTiledLayer(me.game.currentLevel.realwidth,
me.game.currentLevel.realheight));return b},clearTile:function(a,b){for(var c=this.mapLayers.length;c--;)(this.mapLayers[c].visible||this.mapLayers[c].isCollisionMap)&&this.mapLayers[c].clearTile(a,b)},addTo:function(a){this.visible&&a.add(this);for(var b=this.mapLayers.length;b--;)this.mapLayers[b].visible&&a.add(this.mapLayers[b])},update:function(){return!1}});me.levelDirector=function(){var a={},b={},e=null;a.reset=function(){};a.addLevel=function(){throw"melonJS: no level loader defined";};a.addTMXLevel=
function(a,c){null==b[a]&&(b[a]=new me.TMXTileMap(a,0,0));c&&c()};a.loadLevel=function(a){if(b[a]===c)throw"melonJS: level "+a+" not found";if(b[a]instanceof me.TMXTileMap){var d=me.state.isRunning();d&&me.state.pause();me.game.reset();me.utils.resetGUID(a);b[a].reset();b[a].load();e=a;me.game.loadTMXLevel(b[e]);d&&me.state.resume()}else throw"melonJS: no level loader defined";};a.getCurrentLevelId=function(){return e};a.reloadLevel=function(){return a.loadLevel(e)};a.nextLevel=function(){return e+
1<b.length?a.loadLevel(e+1):!1};a.previousLevel=function(){return 0<=e-1?a.loadLevel(e-1):!1};return a}()})(window);
(function(){me.TMX_TAG_MAP="map";me.TMX_TAG_NAME="name";me.TMX_TAG_VALUE="value";me.TMX_TAG_VERSION="version";me.TMX_TAG_ORIENTATION="orientation";me.TMX_TAG_WIDTH="width";me.TMX_TAG_HEIGHT="height";me.TMX_TAG_OPACITY="opacity";me.TMX_TAG_TRANS="trans";me.TMX_TAG_TILEWIDTH="tilewidth";me.TMX_TAG_TILEHEIGHT="tileheight";me.TMX_TAG_TILEOFFSET="tileoffset";me.TMX_TAG_FIRSTGID="firstgid";me.TMX_TAG_GID="gid";me.TMX_TAG_TILE="tile";me.TMX_TAG_ID="id";me.TMX_TAG_DATA="data";me.TMX_TAG_COMPRESSION="compression";
me.TMX_TAG_ENCODING="encoding";me.TMX_TAG_ATTR_BASE64="base64";me.TMX_TAG_CSV="csv";me.TMX_TAG_SPACING="spacing";me.TMX_TAG_MARGIN="margin";me.TMX_TAG_PROPERTIES="properties";me.TMX_TAG_PROPERTY="property";me.TMX_TAG_IMAGE="image";me.TMX_TAG_SOURCE="source";me.TMX_TAG_VISIBLE="visible";me.TMX_TAG_TILESET="tileset";me.TMX_TAG_LAYER="layer";me.TMX_TAG_OBJECTGROUP="objectgroup";me.TMX_TAG_OBJECT="object";me.TMX_TAG_X="x";me.TMX_TAG_Y="y";me.TMX_TAG_WIDTH="width";me.TMX_TAG_HEIGHT="height"})(window);
(function(){me.TMXUtils=function(){return{setTMXProperties:function(b,c){var a=c.getElementsByTagName(me.TMX_TAG_PROPERTIES)[0];if(a)for(var a=a.getElementsByTagName(me.TMX_TAG_PROPERTY),e=0;e<a.length;e++){var d=me.XMLParser.getStringAttribute(a[e],me.TMX_TAG_NAME),f=me.XMLParser.getStringAttribute(a[e],me.TMX_TAG_VALUE);!f||f.isBoolean()?f=f?"true"==f:!0:f.isNumeric()&&(f=parseInt(f));b[d]=f}}}}()})(window);
(function(){me.TMXOBjectGroup=Object.extend({init:function(b,c,a,e){this.objects=[];this.name=b;this.width=me.XMLParser.getIntAttribute(c,me.TMX_TAG_WIDTH);this.height=me.XMLParser.getIntAttribute(c,me.TMX_TAG_HEIGHT);this.z=e;b=c.getElementsByTagName(me.TMX_TAG_OBJECT);for(c=0;c<b.length;c++)this.objects.push(new TMXOBject(b[c],a,e))},getObjectCount:function(){return this.objects.length},getObjectByIndex:function(b){return this.objects[b]}});TMXOBject=Object.extend({init:function(b,c,a){this.name=
me.XMLParser.getStringAttribute(b,me.TMX_TAG_NAME);this.x=me.XMLParser.getIntAttribute(b,me.TMX_TAG_X);this.y=me.XMLParser.getIntAttribute(b,me.TMX_TAG_Y);this.z=a;(this.gid=me.XMLParser.getIntAttribute(b,me.TMX_TAG_GID,null))?(c=c.getTilesetByGid(this.gid),this.width=c.tilewidth,this.height=c.tileheight,this.spritewidth=this.width,this.y-=this.height,this.image=c.getTileImage(this.gid-c.firstgid)):(this.width=me.XMLParser.getIntAttribute(b,me.TMX_TAG_WIDTH,0),this.height=me.XMLParser.getIntAttribute(b,
me.TMX_TAG_HEIGHT,0));me.TMXUtils.setTMXProperties(this,b)},getObjectPropertyByName:function(b){return this[b]}})})(window);
(function(){me.TMXTilesetGroup=Object.extend({init:function(){this.tilesets=[]},add:function(b){this.tilesets.push(b)},getTilesetByIndex:function(b){return this.tilesets[b]},getTilesetByGid:function(b){for(var c=-1,a=0,e=this.tilesets.length;a<e;a++){if(this.tilesets[a].contains(b))return this.tilesets[a];this.tilesets[a].firstgid==this.tilesets[a].lastgid&&b>=this.tilesets[a].firstgid&&(c=a)}if(-1!=c)return this.tilesets[c];throw"no matching tileset found for gid "+b;}});me.TMXTileset=me.Tileset.extend({init:function(b){this.firstgid=
me.XMLParser.getIntAttribute(b,me.TMX_TAG_FIRSTGID);this.parent(me.XMLParser.getStringAttribute(b,me.TMX_TAG_NAME),me.XMLParser.getIntAttribute(b,me.TMX_TAG_TILEWIDTH),me.XMLParser.getIntAttribute(b,me.TMX_TAG_TILEHEIGHT),me.XMLParser.getIntAttribute(b,me.TMX_TAG_SPACING,0),me.XMLParser.getIntAttribute(b,me.TMX_TAG_MARGIN,0),b.getElementsByTagName(me.TMX_TAG_IMAGE)[0].getAttribute(me.TMX_TAG_SOURCE));this.lastgid=this.firstgid+(this.hTileCount*this.vTileCount-1||0);this.trans=b.getElementsByTagName(me.TMX_TAG_IMAGE)[0].getAttribute(me.TMX_TAG_TRANS);
if(null!==this.trans&&this.image)this.image=me.video.applyRGBFilter(this.image,"transparent",this.trans.toUpperCase()).canvas;this.tileoffset=new me.Vector2d(0,0);var c=b.getElementsByTagName(me.TMX_TAG_TILEOFFSET);if(0<c.length)this.tileoffset.x=me.XMLParser.getIntAttribute(c[0],me.TMX_TAG_X),this.tileoffset.y=me.XMLParser.getIntAttribute(c[0],me.TMX_TAG_Y);b=b.getElementsByTagName(me.TMX_TAG_TILE);for(c=0;c<b.length;c++){var a=me.XMLParser.getIntAttribute(b[c],me.TMX_TAG_ID)+this.firstgid;this.TileProperties[a]=
{};a=this.TileProperties[a];me.TMXUtils.setTMXProperties(a,b[c]);a.isSolid=a.type?a.type.toLowerCase()===this.type.SOLID:!1;a.isPlatform=a.type?a.type.toLowerCase()===this.type.PLATFORM:!1;a.isLeftSlope=a.type?a.type.toLowerCase()===this.type.L_SLOPE:!1;a.isRightSlope=a.type?a.type.toLowerCase()===this.type.R_SLOPE:!1;a.isBreakable=a.type?a.type.toLowerCase()===this.type.BREAKABLE:!1;a.isLadder=a.type?a.type.toLowerCase()===this.type.LADDER:!1;a.isSlope=a.isLeftSlope||a.isRightSlope;a.isCollidable=
a.isSolid||a.isPlatform||a.isSlope||a.isLadder||a.isBreakable}},contains:function(b){return b>=this.firstgid&&b<=this.lastgid}})})(window);
(function(){TMXRenderer=Object.extend({init:function(b,c,a,e,d){this.predraw=b;this.width=c;this.height=a;this.tilewidth=e;this.tileheight=d},drawTile:function(){}});me.TMXOrthogonalRenderer=TMXRenderer.extend({drawTile:function(b,c,a,e,d,f,g){d.drawTile(b,d.tileoffset.x+c*this.tilewidth,d.tileoffset.y+(a+1)*this.tileheight-d.tileheight,e-d.firstgid,f,g)}});me.TMXIsometricRenderer=TMXRenderer.extend({drawTile:function(b,c,a,e,d,f,g){d.drawTile(b,(this.width-1)*d.tilewidth+(c-a)*d.tilewidth>>1,-d.tilewidth+
(c+a)*d.tileheight>>2,e-d.firstgid,f,g)}})})(window);
(function(){me.TMXTileMap=me.TileMap.extend({init:function(b,c,a){this.parent(c,a);this.xmlMap=me.loader.getXML(b);if(!this.xmlMap)throw"melonJS:"+b+" TMX map not found";this.orientation=this.version="";this.tilesets=this.tileMapCanvas=null},load:function(){if(!this.initialized){var b=0,c=1;me.XMLParser.parseFromString(this.xmlMap);for(var a=me.XMLParser.getAllTagElements(),e=0;e<a.length;e++)switch(a.item(e).nodeName){case me.TMX_TAG_MAP:var d=a.item(e);this.version=me.XMLParser.getStringAttribute(d,
me.TMX_TAG_VERSION);this.orientation=me.XMLParser.getStringAttribute(d,me.TMX_TAG_ORIENTATION);this.width=me.XMLParser.getIntAttribute(d,me.TMX_TAG_WIDTH);this.height=me.XMLParser.getIntAttribute(d,me.TMX_TAG_HEIGHT);this.tilewidth=me.XMLParser.getIntAttribute(d,me.TMX_TAG_TILEWIDTH);this.tileheight=me.XMLParser.getIntAttribute(d,me.TMX_TAG_TILEHEIGHT);this.realwidth=this.width*this.tilewidth;this.realheight=this.height*this.tileheight;this.z=b++;me.TMXUtils.setTMXProperties(this,d);this.visible=
!1;if(this.background_color)this.visible=!0,this.background_color=me.utils.HexToRGB(this.background_color);if(this.background_image)this.visible=!0,this.background_image=me.loader.getImage(this.background_image);break;case me.TMX_TAG_TILESET:if(!this.tilesets)this.tilesets=new me.TMXTilesetGroup;this.tilesets.add(new me.TMXTileset(a.item(e)));break;case me.TMX_TAG_LAYER:if(me.XMLParser.getStringAttribute(a.item(e),me.TMX_TAG_NAME).toLowerCase().contains(me.LevelConstants.PARALLAX_MAP)){if(1==me.XMLParser.getIntAttribute(a.item(e),
me.TMX_TAG_VISIBLE,1)){d={};me.TMXUtils.setTMXProperties(d,a.item(e));var f=this.getLayerByName(me.LevelConstants.PARALLAX_MAP);f||(f=new me.ParallaxBackgroundEntity(b),this.mapLayers.push(f));f.addLayer(d.imagesrc,c++,b++)}}else this.mapLayers.push(new me.TMXLayer(a.item(e),this.tilewidth,this.tileheight,this.orientation,this.tilesets,b++)),b++;break;case me.TMX_TAG_OBJECTGROUP:d=me.XMLParser.getStringAttribute(a.item(e),me.TMX_TAG_NAME),this.objectGroups.push(new me.TMXOBjectGroup(d,a.item(e),this.tilesets,
b++))}me.XMLParser.free();this.initialized=!0}},draw:function(b,c){if(this.background_color)b.fillStyle=this.background_color,b.fillRect(c.left,c.top,c.width,c.height);this.background_image&&b.drawImage(this.background_image,c.left,c.top,c.width,c.height,c.left,c.top,c.width,c.height)}});me.TMXLayer=me.TiledLayer.extend({init:function(b,c,a,e,d,f){this.parent(me.XMLParser.getIntAttribute(b,me.TMX_TAG_WIDTH),me.XMLParser.getIntAttribute(b,me.TMX_TAG_HEIGHT),c,a,d,f);this.orientation=e;this.layerInvalidated=
!0;this.name=me.XMLParser.getStringAttribute(b,me.TMX_TAG_NAME);this.visible=1==me.XMLParser.getIntAttribute(b,me.TMX_TAG_VISIBLE,1);this.opacity=me.XMLParser.getFloatAttribute(b,me.TMX_TAG_OPACITY,1);me.TMXUtils.setTMXProperties(this,b);if(this.isCollisionMap=this.name.toLowerCase().contains(me.LevelConstants.COLLISION_MAP))this.visible=!1;this.vp=me.game.viewport;b=b.getElementsByTagName(me.TMX_TAG_DATA)[0];c=me.XMLParser.getStringAttribute(b,me.TMX_TAG_ENCODING,null);a=me.XMLParser.getStringAttribute(b,
me.TMX_TAG_COMPRESSION,null);""==c&&(c=null);""==a&&(a=null);if(this.visible){switch(this.orientation){case "orthogonal":this.renderer=new me.TMXOrthogonalRenderer(!0,this.width,this.height,this.tilewidth,this.tileheight);break;case "isometric":this.renderer=new me.TMXIsometricRenderer(!0,this.width,this.height,this.tilewidth,this.tileheight);break;default:throw"melonJS: "+this.orientation+" type TMX Tile Map not supported!";}this.layerSurface=me.video.createCanvasSurface(this.width*this.tilewidth,
this.height*this.tileheight);this.layerCanvas=this.layerSurface.canvas;if(0<this.opacity&&1>this.opacity)this.layerSurface.globalAlpha=this.opacity}if(this.visible||this.isCollisionMap)this.initArray(this.isCollisionMap),this.fillArray(b,c,a)},fillArray:function(b,c,a){switch(a){case null:switch(c){case null:b=b.getElementsByTagName(me.TMX_TAG_TILE);break;case me.TMX_TAG_CSV:case me.TMX_TAG_ATTR_BASE64:for(var a="",e=0,d=b.childNodes.length;e<d;e++)a+=b.childNodes[e].nodeValue;b=c==me.TMX_TAG_ATTR_BASE64?
me.utils.decodeBase64AsArray(a,4):me.utils.decodeCSV(a,this.width);break;default:throw"melonJS: TMX Tile Map "+c+" encoding not supported!";}break;default:throw"melonJS: "+a+" compressed TMX Tile Map not supported!";}for(var a=0,f,g=0;g<this.height;g++)for(var i=0;i<this.width;i++)if(f=null==c?me.XMLParser.getIntAttribute(b[a++],me.TMX_TAG_GID):b[a++],e=f&2147483648,d=f&1073741824,f&=1073741823,0<f){this.setTile(i,g,f);if(!this.tileset.contains(f))this.tileset=this.tilesets.getTilesetByGid(f);this.visible&&
this.renderer.drawTile(this.layerSurface,i,g,f,this.tileset,e,d)}},clearTile:function(b,c){this.parent(b,c);this.visible&&this.layerSurface.clearRect(b*this.tilewidth,c*this.tileheight,this.tilewidth,this.tileheight)},draw:function(b,c){b.drawImage(this.layerCanvas,this.vp.pos.x+c.pos.x,this.vp.pos.y+c.pos.y,c.width,c.height,c.pos.x,c.pos.y,c.width,c.height)}})})(window);
(function(){me.Tween=function(b){var c={},a={},e={},d=1E3,f=0,g=null,i=me.Tween.Easing.Linear.EaseNone,h=null,j=null,k=null;this.to=function(a,c){null!==c&&(d=c);for(var f in a)null!==b[f]&&(e[f]=a[f]);return this};this.start=function(){me.game.add(this,999);g=me.timer.getTime()+f;for(var d in e)null!==b[d]&&(c[d]=b[d],a[d]=e[d]-b[d]);return this};this.stop=function(){me.game.remove(this);return this};this.delay=function(a){f=a;return this};this.easing=function(a){i=a;return this};this.chain=function(a){h=
a};this.onUpdate=function(a){j=a;return this};this.onComplete=function(a){k=a;return this};this.update=function(){var e,f,n;f=me.timer.getTime();if(f<g)return!0;f=(f-g)/d;f=1<f?1:f;n=i(f);for(e in a)b[e]=c[e]+a[e]*n;null!==j&&j.call(b,n);return 1==f?(me.game.remove(this),null!==k&&k.call(b),null!==h&&h.start(),!1):!0};this.destroy=function(){return!0}};me.Tween.Easing={Linear:{},Quadratic:{},Cubic:{},Quartic:{},Quintic:{},Sinusoidal:{},Exponential:{},Circular:{},Elastic:{},Back:{},Bounce:{}};me.Tween.Easing.Linear.EaseNone=
function(b){return b};me.Tween.Easing.Quadratic.EaseIn=function(b){return b*b};me.Tween.Easing.Quadratic.EaseOut=function(b){return-b*(b-2)};me.Tween.Easing.Quadratic.EaseInOut=function(b){return 1>(b*=2)?0.5*b*b:-0.5*(--b*(b-2)-1)};me.Tween.Easing.Cubic.EaseIn=function(b){return b*b*b};me.Tween.Easing.Cubic.EaseOut=function(b){return--b*b*b+1};me.Tween.Easing.Cubic.EaseInOut=function(b){return 1>(b*=2)?0.5*b*b*b:0.5*((b-=2)*b*b+2)};me.Tween.Easing.Quartic.EaseIn=function(b){return b*b*b*b};me.Tween.Easing.Quartic.EaseOut=
function(b){return-(--b*b*b*b-1)};me.Tween.Easing.Quartic.EaseInOut=function(b){return 1>(b*=2)?0.5*b*b*b*b:-0.5*((b-=2)*b*b*b-2)};me.Tween.Easing.Quintic.EaseIn=function(b){return b*b*b*b*b};me.Tween.Easing.Quintic.EaseOut=function(b){return(b-=1)*b*b*b*b+1};me.Tween.Easing.Quintic.EaseInOut=function(b){return 1>(b*=2)?0.5*b*b*b*b*b:0.5*((b-=2)*b*b*b*b+2)};me.Tween.Easing.Sinusoidal.EaseIn=function(b){return-Math.cos(b*Math.PI/2)+1};me.Tween.Easing.Sinusoidal.EaseOut=function(b){return Math.sin(b*
Math.PI/2)};me.Tween.Easing.Sinusoidal.EaseInOut=function(b){return-0.5*(Math.cos(Math.PI*b)-1)};me.Tween.Easing.Exponential.EaseIn=function(b){return 0==b?0:Math.pow(2,10*(b-1))};me.Tween.Easing.Exponential.EaseOut=function(b){return 1==b?1:-Math.pow(2,-10*b)+1};me.Tween.Easing.Exponential.EaseInOut=function(b){return 0==b?0:1==b?1:1>(b*=2)?0.5*Math.pow(2,10*(b-1)):0.5*(-Math.pow(2,-10*(b-1))+2)};me.Tween.Easing.Circular.EaseIn=function(b){return-(Math.sqrt(1-b*b)-1)};me.Tween.Easing.Circular.EaseOut=
function(b){return Math.sqrt(1- --b*b)};me.Tween.Easing.Circular.EaseInOut=function(b){return 1>(b/=0.5)?-0.5*(Math.sqrt(1-b*b)-1):0.5*(Math.sqrt(1-(b-=2)*b)+1)};me.Tween.Easing.Elastic.EaseIn=function(b){var c,a=0.1,e=0.4;if(0==b)return 0;if(1==b)return 1;e||(e=0.3);!a||1>a?(a=1,c=e/4):c=e/(2*Math.PI)*Math.asin(1/a);return-(a*Math.pow(2,10*(b-=1))*Math.sin((b-c)*2*Math.PI/e))};me.Tween.Easing.Elastic.EaseOut=function(b){var c,a=0.1,e=0.4;if(0==b)return 0;if(1==b)return 1;e||(e=0.3);!a||1>a?(a=1,
c=e/4):c=e/(2*Math.PI)*Math.asin(1/a);return a*Math.pow(2,-10*b)*Math.sin((b-c)*2*Math.PI/e)+1};me.Tween.Easing.Elastic.EaseInOut=function(b){var c,a=0.1,e=0.4;if(0==b)return 0;if(1==b)return 1;e||(e=0.3);!a||1>a?(a=1,c=e/4):c=e/(2*Math.PI)*Math.asin(1/a);return 1>(b*=2)?-0.5*a*Math.pow(2,10*(b-=1))*Math.sin((b-c)*2*Math.PI/e):0.5*a*Math.pow(2,-10*(b-=1))*Math.sin((b-c)*2*Math.PI/e)+1};me.Tween.Easing.Back.EaseIn=function(b){return b*b*(2.70158*b-1.70158)};me.Tween.Easing.Back.EaseOut=function(b){return(b-=
1)*b*(2.70158*b+1.70158)+1};me.Tween.Easing.Back.EaseInOut=function(b){return 1>(b*=2)?0.5*b*b*(3.5949095*b-2.5949095):0.5*((b-=2)*b*(3.5949095*b+2.5949095)+2)};me.Tween.Easing.Bounce.EaseIn=function(b){return 1-Tween.Easing.Bounce.EaseOut(1-b)};me.Tween.Easing.Bounce.EaseOut=function(b){return(b/=1)<1/2.75?7.5625*b*b:b<2/2.75?7.5625*(b-=1.5/2.75)*b+0.75:b<2.5/2.75?7.5625*(b-=2.25/2.75)*b+0.9375:7.5625*(b-=2.625/2.75)*b+0.984375};me.Tween.Easing.Bounce.EaseInOut=function(b){return 0.5>b?0.5*Tween.Easing.Bounce.EaseIn(2*
b):0.5*Tween.Easing.Bounce.EaseOut(2*b-1)+0.5}})(window);
